### ISSUE TITLE
Export and Generics

### ISSUE THREAD

**Issue by isBatak** [NinoMaj/carousel-virtualized#10]
https://github.com/NinoMaj/carousel-virtualized/blob/cc254d02a80d9ea7284ffe81908064ed9812441c/src/components/Slider/Slider.tsx#L148
you can export it like this
```
export class Slider extends React.Component<ISliderProps> { 
...
```
and it is prettier to write generics in the same line 
`export class Example extends Base<Generic> { ... }`

**Comment by NinoMaj** [comment]
I am on the fence with this, since I like that all imports are in the beginning of a file and all exports in the end.
